name: CI

on: [push]

jobs:
  build_and_test:
    name: Build and test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["5.1.0"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: fwal/setup-swift@master
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -v
    - name: Tests
      run: swift test -v
