name: CI

on:
  - push

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "swift:5.1"
      name: Linux
      runs-on: ubuntu-latest
      container:
        image: ${{ matrix.image }}
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Version
          uses: swift --version
        - name: Build
          uses: swift build -v -c debug
        - name: Test
          uses: swift test -v -c debug

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Version
        uses: swift --version
      - name: Build
        uses: swift build -v -c debug
      - name: Test
        uses: swift test -v -c debug
