name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: macos-15 # go back to macos-latest once 15 becomes the default
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Tests
      run: swift test -v
