name: CI

on: [push]

jobs:
  build_and_test:
    name: Build and test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Tests
      run: swift test -v
